<div class="content">
    <div class="content byEditor about">
        <h1>Scottish Government Yearbook: a History</h1>

        <p><em><strong>The editors of the final SGY <a href="http://www.sps.ed.ac.uk/staff/sociology/mccrone_david" target="_blank">David McCrone</a> and <a href="http://www.sps.ed.ac.uk/staff/social_policy/lindsay_paterson" target="_blank"><strong>Lindsay Paterson</strong></a> reflect on the back-story of the </strong></em><strong>Yearbooks</strong> <em><strong>&#8230;</strong></em></p>
        <p >‘Scotland is a perplexing place at present. It is on the threshold of a major constitutional reform which will greatly enhance its political life and which will change the course of history in unpredictable ways.’</p>
        <p>These were the opening lines <strong>Henry Drucker</strong> wrote in the first edition of <em>Scottish Government Yearbook</em> in 1976. If they could equally describe present conditions, in 2014, they are a mark of how much, as well as how little, has changed in Scotland almost 40 years later.</p>
        <p>What he would have made of developments since he died in 2002 is a matter for speculation, although he probably would still hold to his view in the last lines of that first editorial that ‘Partly because of the political changes going on within it, Scotland is alive and exciting. Its government is much more interesting than it was until very recently, and to us at least, it makes the rest of Great Britain seem dull’.</p>
        <p>An American, Henry Drucker came to Edinburgh in 1967 to teach political theory, having completed a PhD ‘The Political Uses of Ideology’ at the London School of Economics. Arriving in Edinburgh, he took to the practice as well as the study of Scottish politics as a duck to water. He was close to that generation of Labour politicians like Robin Cook (he was his constituency chairman in Edinburgh Central) and Gordon Brown, with whom he co-wrote <em>The Politics of Nationalism and Devolution</em> in 1980.</p>
        <p>It was this experience which caused him to write his book <em>Doctrine and Ethos in the Labour Party </em>(1979). His interest in Scottish politics led him to write <em>Breakaway: The Scottish Labour Party</em> (EUSPB, 1977), an account of the short-lived political party led by Jim Sillars. He also edited <em>John P. Mackintosh on Scotland</em> (Longman, 1982) the writings on Scotland of John P. Mackintosh, politician and academic who died in 1978, and, with his students, wrote ‘Learning to Fight Multi-Party Elections: the lessons of Hillhead’ (<em>Parliamentary Affairs</em>, Summer, 1982), a study of how Roy Jenkins won the seat at a by-election in 1982.</p>
        <p>Henry’s rationale for setting up the <strong>Unit for the Study of Government in Scotland</strong> (USGS) was the hope that ‘it might act as a catalyst by bringing together people from inside and outside the world of government to discuss [these] issues’. The <em>Scottish Government Yearbook</em> (SGY) was to be its vehicle, to be at the centre of debate about government in Scotland, with contributions from practitioners and academics alike, but only if the latter eschewed copious and boring footnotes. The first edition, <em>Our Changing Scotland</em>, edited by Henry and <strong>Michael Clarke</strong>, was dedicated ‘to the much maligned governors of Scotland’, making the country sound a bit like a jail.</p>
        <p>As a yearbook, <em>SGY</em> had a bibliographic and a reference section, with <strong>Chris Allen</strong> providing the former, and <strong>Allan Macartney</strong> a review of opinion polls. <strong>Jim Naughtie</strong>, at the time political editor of <em>The Scotsman</em>, wrote ‘the year at Westminster’. <strong>John Bochel</strong> and <strong>David Denver</strong> analysed election results, and <strong>Hamish (McNair) Henderson</strong> reviewed Scottish legislation.</p>
        <p>The first yearbook, <em>Our Changing Scotland</em>, was published by Edinburgh University Students Publication Board (EUSPB) which had published Gordon Brown’s <em>Red Paper on Scotland</em> in 1975. Henry subsequently found a local (very) small publisher, Paul Harris, who published the <em>Yearbook</em> between 1978 and 1982.</p>
        <p>Michael Clarke who had co-edited <em>SGY</em> in its first two editions went off to work in Policy Planning at Lothian Regional Council, and Henry’s wife <strong>Nancy</strong>, who taught in the Department of Social Administration, co-edited the three editions between 1979 and 1982.</p>
        <p>Henry encouraged a catholic view of Scottish politics and government, and had involved colleagues in constitutional law, social policy/administration, as well as sociology. There was no question that only political scientists could make sense of Scottish politics, and in any case, specialising in such a subject as Scotland was not seen as a good career move.</p>
        <p>The next five editions of <em>SGY</em> (1983 to 1987) were edited by <strong>David McCrone</strong> on his own. He had to find a new publisher in-house, the Research Centre for Social Sciences (RCSS), and its printing section, because the arrangement with Paul Harris, the previous publisher, had ended. In lieu of royalties, Harris donated past copies of <em>SGY</em>, most of which still linger in the vaults of Chisholm House, and copies of SGY can be had simply for the effort of a trip to High School Yards.</p>
        <p>Between 1988 and 1992, <em>SGY</em> had co-editors, David McCrone and <strong>Alice Brown</strong> (1988 and 1989); <strong>Alice Brown</strong> and <strong>Richard Parry</strong> (1990); Alice Brown and David McCrone (1991), and finally <strong>Lindsay Paterson</strong> and David McCrone for the final 1992 edition.</p>
        <p>The in-house publishing arrangement with RCSS, a hands-on experience, long before the days of digital printing, continued until 1992 when <em>SGY</em> was transformed into a quarterly, <strong><a href="http://www.euppublishing.com/journal/scot" target="_blank"><em>Scottish Affairs</em></a></strong>, edited by Lindsay Paterson. By this time, it became clear that an annual publication was simply not up to the gathering pace of Scottish politics, and taking a chance on a quarterly publication with substantially higher costs was a challenge ably met by Lindsay Paterson. Lindsay continued the demanding task of editing and publishing <em>Scottish Affairs</em>. Another Lindsay – <strong>Lindsay Adams</strong> &#8211; did the sales and marketing for <em>Scottish Affairs</em> which was published by subscription all the way down to 2014, when Edinburgh University Press took over the publishing.</p>
        <p>More than 200 people contributed to the <em>Yearbook</em> over its 16 editions. Much depended on its contributors being prepared to write, gratis, for the <em>Yearbook</em>. It was reliant on a number of people who made the <em>Yearbook</em> happen: <strong>Helen Ramm</strong> who acted as its secretary, <strong>John Nimmo</strong> and his colleagues in RCSS who did the printing, Chris Allen for his comprehensive bibliographic essay, Allan Macartney for his review of polls, Hamish Henderson for his law review, the various editors who had to cajole contributors to meet deadlines, and more generally the steering committee of USGS, notably <strong>Charlie Raab</strong>, who made helpful suggestions.</p>
        <p>Writing for <em>SGY</em>, and <em>Scottish Affairs</em>, was not an especially good career move as universities entered the days of research assessment exercises, and the modern university obsession with ‘impact’. Authors simply wrote for a public audience in the days before it became fashionable. They took the academic low road because they felt they had something to say about Scotland. The academic high road took the form of writing in academic journals, or in publishing books (the kind with lots of learned footnotes for the attention of referees).</p>
        <p>Would any of this have come to pass without Henry Drucker? It is impossible to say, of course, but it is unlikely. It is something of a surprise to discover that he (co)edited only 5 out of the 16 Yearbooks, but they helped to lay out the future. Henry was enthused about what he found when he came to Scotland, and treated as interesting what others simply ignored or took for granted. In establishing the <em>Y</em><em>ea</em><em>rbook</em>, and more generally the Unit for the Study of Government in Scotland, and alongside teaching courses on Scottish Government and Politics, Henry helped to lay the basis for Edinburgh becoming a major centre for multidisciplinary research, teaching and writing. His broad conspectus that the study of politics and government was not the preserve simply of ‘Politics’ served Edinburgh well. It was the case that there were too few political scientists at the time interested in Scotland, and involving other social scientists in the endeavour was both necessary and valuable.</p>
        <p>In any case, the study of Scotland had a wide pedigree into which SGY and USGS fitted. <strong>Harry Hanham</strong>, the first professor of politics at Edinburgh in 1963, had published his book <em>Scottish Nationalism</em> in 1969. In the same year, <strong>Christopher Smout</strong> in Social and Economic History had published <em>A History of the Scottish People, 1560-1830</em>, and his companion volume, <em>A Century of the Scottish People, 1830-1950</em>, in 1986. Over in Law, <strong>Neil MacCormick</strong> was the star in the firmament since his appointment in 1972. In Glasgow, <strong>James Kellas</strong> ploughed a productive furrow in Scottish politics, while <strong>Tom Nairn</strong>’s illuminating writings, notably his <em>Break-Up of Britain</em> (1977), made an impact well beyond the academy.</p>
        <p>The transformation of politics in Scotland, of which the rise of the SNP was a key part, stimulated writing and study, and in such a way that conventional barriers between academic subjects were of little relevance. USGS itself ultimately became the <a href="http://www.institute-of-governance.org/" target="_blank"><strong>Institute of Governance</strong></a> in 1998, co-directed by Alice Brown and David McCrone, by way of the <strong>Governance of Scotland Forum</strong>.</p>
        <p>By the mid-1980s, Henry had found a new enthusiasm as a fund-raiser for the university, and by 1987 was appointed as Oxford University’s first director of development. He built a formidable and highly successful outfit bringing in major benefactions. In 1993, he left to set up his own consultancy, Oxford Philanthropic, to advise charities and education bodies on attracting external funds. Despite his Labour links, he fell out with the party in 1996 over the issue of ‘blind trusts’ whereby donors could make anonymous donations. On being elected in 1997, Blair’s Labour government ran into its first financial scandal, the Ecclestone affair. In response, one can hear Henry’s trademark ‘Quite’, said with a wry smile.</p>
        <p>Henry died in 2002, at the age of 60, after a long history of heart disease. <em>Scottish Government Yearbook</em> was his creation, with succeeding editors developing it in new ways. We owe a debt to <strong>Michael Rosie</strong>, and to Edinburgh University Library, for making this Archive happen. The study of Scottish politics and government at Edinburgh has long relied on the selfless commitment and enthusiasm of many people. This archive is an important part of their legacy.</p>
        <p><a href="http://www.sps.ed.ac.uk/staff/sociology/mccrone_david" target="_blank"><strong>David McCrone</strong></a> and <a href="http://www.sps.ed.ac.uk/staff/social_policy/lindsay_paterson" target="_blank"><strong>Lindsay Paterson</strong></a> (November, 2014)</p>


    </div>
</div>